
# ------ Port -----
server.port = 8081

# ------ App ------
spring.application.name=minerai

# ------ Database ------
spring.datasource.url=jdbc:postgresql://localhost:5432/project_manager_db
spring.datasource.username=postgres
spring.datasource.password=newpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ------ JPA / Hibernate ------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ------ Security ------
logging.level.org.springframework.security=DEBUG

# ------ JWT ------
jwt.secret=03120ac7327a23680090762bdc9cc7bc
# -- 15 minutes
jwt.access-token-expiration=900000
# -- 7 days
jwt.refresh-token-expiration=604800000

# ------ Frontend URL ------
app.frontend.url=http://localhost:3000

# ------ Email / SMTP Configuration ------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omarsahmoud02@gmail.com
spring.mail.password=jise zydz ocno rlgz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=minersteam@gmail.com